on: 
  push:
    branches:
    - staging
name: Deploy to Test
jobs:
  pushToTest:
    name: Push to Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15'
    - run: npm run-script build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: aws s3 cp /home/runner/work/TravelTime/TravelTime/dist/ s3://test.streamstats.usgs.gov/tot/ --recursive
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@9273a038d94644256c1ba855c9ed6f4391b9cd89
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: Successfully deployed to https://test.streamstats.usgs.gov/tot
